# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 17:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=90)),
                ('lastname', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(14)])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
